#!/bin/bash

# ---------------------------------------------------------------------------------------------------------------------

# Bash While Loops

# What is a while loop?
# A while loop allows you to execute a block of code repeatedly as long as a specified condition is true.

# Why use while loops?
# While loops are useful when you want to repeat a block of code an unknown number of times,
# or when you want to repeat a block of code until a certain condition is met.

# How do while loops work?
# Here is the basic syntax for a while loop:
# while condition; do
#     # do something exciting here
# done

# Example 1):
counter=1
while [ $counter -le 5 ]; do
    echo "number $counter"
    counter=$((counter + 1))
done
# Output: number 1
# Output: number 2
# Output: number 3
# Output: number 4
# Output: number 5
# In this example, the while loop continues to execute as long as the condition [ $counter -le 5 ] is true.
# The variable `counter` starts at 1 and is incremented by 1 for each repetition of the loop until it is greater than 5.

