#!/bin/bash

# ---------------------------------------------------------------------------------------------------------------------

# Bash While Loops

# What is a while loop?
# A while loop allows you to execute a block of code repeatedly as long as a specified condition is true.

# Why use while loops?
# While loops are useful when you want to repeat a block of code an unknown number of times,
# or when you want to repeat a block of code until a certain condition is met.

